### ISSUE TITLE
Homepage video not playing on Safari, needs "Range" request header

### ISSUE THREAD

**Issue by lukehollis** [artshumrc/giza#111]
From Peter: "Giza Plateau rotates fine on the home page in Chrome on both Mac OS and iPad. But in Safari, both on the Mac and on the iPad, it’s static. So definitely a Safari browser issue."

**Comment by lukehollis** [comment]
@rsinghal and @ColeDCrawford I was only able to get this working by hosting the video files separately from Django's static file server to support the Range request code Safari needs as discussed here: https://stackoverflow.com/questions/27712778/video-plays-in-other-browsers-but-not-safari#answer-36299252 -- and some potential Django implementations for a workaround here: https://stackoverflow.com/questions/14324250/byte-ranges-in-django

Adding the files separately on s3 is an immediate workaround that I have here but won't submit a PR for since they're on a separate bucket: https://github.com/lukehollis/giza/commit/85ece99169bac2cf55fecd9f1b4c12e3891a8640 

If you let me know what you prefer for static file hosting to support the Safari range request, I can implement that solution.

**Comment by rsinghal** [comment]
If it just needs to be hosted separately, @npicardo can add it to dbmedia and then we should have a link to it.

**Comment by npicardo** [comment]
@rsinghal @lukehollis 

Available in 3 formats (MP4, OGV, WEBM), all with file name GizaHome_web
\\rcstore02.rc.fas.harvard.edu\giza\dbmedia\images\website

**Comment by rsinghal** [comment]
URLs will look like this: http://gizamedia.rc.fas.harvard.edu/images/website/GizaHome_web.[ext]
