### ISSUE TITLE
Tomb search result buried

### ISSUE THREAD

**Issue by pmanuelian** [artshumrc/giza#127]
Adjust search results so that "G 2110" (example) shows at top of list, as before, not buried out of order. The older screenshot shows G 2110 at top of list. The new search result makes G 2110 hard to find.
Same problem with searching for an object, such as "12.1484" (a statue). The results used to display clearly.

![New_G2110_search_reduced](https://user-images.githubusercontent.com/24411674/107701296-b6030200-6c86-11eb-9c5c-a6f9d68c3f50.jpg)
![Original_easy_G2110_search](https://user-images.githubusercontent.com/24411674/107701297-b69b9880-6c86-11eb-9264-10af8e926a51.jpg)

Similarly, searching for a line drawing "EG023553" produces either far too many results from the search box on the home page, or no results in advanced search > ID number box.

**Comment by lukehollis** [comment]
This is likely related to fuzzy string search matching--with no space between "G" and "2110" we get the following results in what appears to be the desired order. Can you confirm that these results are displaying correctly, @pmanuelian @npicardo?   

<img width="1247" alt="Screen Shot 2021-02-15 at 11 10 46 AM" src="https://user-images.githubusercontent.com/2633382/107985390-df6da780-6f7e-11eb-991a-1e565618af87.png">

Whereas if we add a space between "G" and "2110" it seems like we get the less relevant results: 

<img width="1244" alt="Screen Shot 2021-02-15 at 11 14 25 AM" src="https://user-images.githubusercontent.com/2633382/107985468-fa401c00-6f7e-11eb-957d-c6cb90a1e79e.png">

I'm wondering if changing the way the space is handled would display the correct search results.
