### ISSUE TITLE
Search results are strange

### ISSUE THREAD

**Issue by ColeDCrawford** [artshumrc/giza#156]

**Comment by ColeDCrawford** [comment]
Test search: "Chapel" [https://giza-web2.rc.fas.harvard.edu/search-results/?q=chapel](https://giza-web2.rc.fas.harvard.edu/search-results/?q=chapel). The top results, and many of the others, do not have the word chapel anywhere in the JSON. There are far too many results. The search seems to have a lot of regressions introduced in the past 6 months. See [https://github.com/artshumrc/giza/issues/127](https://github.com/artshumrc/giza/issues/127) for instance.

![Screen Shot 2021-03-31 at 11 38 54 AM](https://user-images.githubusercontent.com/16374762/113171813-d9bddf80-9215-11eb-9717-3797c623efd8.png)

**Comment by rsinghal** [comment]
fixed with #163
