### ISSUE TITLE
Add Django Groups for User permissions

### ISSUE THREAD

**Issue by ColeDCrawford** [artshumrc/giza#94]
Eg an "RA" group
@npicardo - can you define these groups and the level of permissions you want each to have?

**Comment by npicardo** [comment]
My apologies, but I'm not sure what this question refers to.

**Comment by ColeDCrawford** [comment]
It's usually easier to have groups to manage permissions for user accounts rather than assign them directly to users, though that could be an option too. So when you add a new RA, they would get added to the RA group that has some permissions (eg edit Django content) but not others (eg administer user accounts).

**Comment by npicardo** [comment]
I think our needs are very basic and binary:  An "admin" user type with full create/delete/edit privileges across the board; and a "Public" type that can only create/delete/edit collections for which they are the owners.

**Comment by lukehollis** [comment]
@ColeDCrawford could you describe what you'd like changed here?

**Comment by ColeDCrawford** [comment]
We need an autocomplete box with a filter for object type. You will need to store both item type and item IDs for each reference because there is no UUID in Elasticsearch to be able to retrieve an item by a single key.

A number of plugins allow for remote URLs to external APIs as data sources for autocomplete. Eg see https://django-autocomplete-light.readthedocs.io/en/v2/remote.html

**Comment by lukehollis** [comment]
To clarify from @ColeDCrawford's/your comments here: 

* An end user ("public") should not be able to access the Django admin dashboard. 
This should be covered in PR #150 
* They should be able to create and delete their own collections, and add and remove items from those collections from the front end.
This should be covered in PR #151
